### ISSUE TITLE
depend on convert 3.1.1

### ISSUE THREAD

**Issue by lastmeta** [inapay/bech32#6]
convert has a new patch, that bech32 isn't known to be compatible with.
```
[serverv2_server] dart pub add wallet_utils
Because every version of wallet_utils depends on bech32 ^0.2.1 which depends on convert >=1.0.0 <3.1.0, every version of wallet_utils requires convert >=1.0.0 <3.1.0.
So, because serverv2_server depends on both convert ^3.1.1 and wallet_utils any, version solving failed.
exit code 65
```

**Comment by ryzizub** [comment]
It is already merged just waiting for a release on pub.dev

**Comment by ethicnology** [comment]
Thanks for upgrading convert to 3.1.1, when can we expect that you publish the new version of bech32 on pub.dev ?

**Comment by haarts** [comment]
As soon as I'm back at my work machine. Which is Monday.

------- Original Message -------

**Comment by ryzizub** [comment]
Hey @haarts how it's looking? 🙂

**Comment by haarts** [comment]
Good of you to remind me! Please continue to do so! But my kids are sick and I'm stuck at home. 😊

**Comment by lastmeta** [comment]
> Hey @haarts how it's looking? 🙂

```
PS C:\moontree\wallet_utils> dart pub get
Resolving dependencies...
Because bech32 0.2.1 depends on convert >=1.0.0 <3.1.0 and no versions
  of bech32 match >0.2.1 <0.3.0, bech32 ^0.2.1 requires convert >=1.0.0   
  <3.1.0.
So, because wallet_utils depends on both bech32 ^0.2.1 and convert        
  ^3.1.1, version solving failed.
```

I went to the pub.dev site https://pub.dev/packages/bech32 and it still says 0.2.1 is the latest, shouldn't the update be 0.2.2 or something?

**Comment by haarts** [comment]
All done! Kids are still sick but for you guys, I made the trip to the office nonetheless. :wink:
